project:
  type: book

lang: de
language: 
  title-block-author-single: "Autor:"
  title-block-published: "Erstellt am:"

book:
  title: "Machine Learning als Unterstützung in der Labormedizin?"
  subtitle: "Data-Minig-Projekt zur Interpretation der Protein-Elektrophorese"
  author: "Oliver Speer"
  date: "10.03.2024"
  editor: visual
  repo-url: 'https://github.com/oliverspeer/CAS-ASDA-EP-ML.git'
  repo-branch: main


  chapters:
    - index.qmd
#    - intro.qmd
    
    - BusinessUnderstanding.qmd
    - DataUnderstanding.qmd
    - DataPreparation.qmd
    - Modeling.qmd
    - Evaluation.qmd
    - Deployment.qmd
    
    - references.qmd

bibliography: my_ref.bib

format:
  html:
    theme: cosmo
    fig-width: 8
    fig-height: 6
    fig-align: "center"
    fig-caption: true
    df-print: kable
    highlight: "monochrome"
    css: cas.css
    code-link: true
    code-fold: true
    code-tools: true
    embed-resources: true
    toc: true
    toc-depth: 4
    toc-title: "Inhalt"
    
    
    

  




